# Generated by Django 4.2.16 on 2024-10-07 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('Coordinator', 'Coordinator'), ('Principle', 'Principle')], default='student', max_length=50),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('it', 'Information Technology'), ('cs', 'Computer Science'), ('entc', 'Electronics and Telecommunication'), ('mech', 'Mechanical'), ('biotech', 'Biotechnology'), ('electrical', 'Electrical'), ('civil', 'Civil')], default='it', max_length=50)),
                ('current_year', models.CharField(choices=[('fe', 'FE'), ('se', 'SE'), ('te', 'TE'), ('be', 'BE')], default='fe', max_length=50)),
                ('prn_no', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('fee_recipt', models.ImageField(default='images/default.png', upload_to='fee_recipts/')),
                ('id_proof', models.ImageField(default='images/default.png', upload_to='id_proof/')),
                ('profile_image', models.ImageField(default='images/default.png', upload_to='profile_pic/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
