# Generated by Django 5.1.1 on 2024-11-09 13:12

import ckeditor.fields
import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_customuser_user_type_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', events.models.NullableCharField(blank=True, max_length=500, null=True)),
                ('address', events.models.NullableCharField(blank=True, max_length=300, null=True)),
                ('head_organizer', events.models.NullableCharField(blank=True, max_length=500, null=True)),
                ('contact_organizer', events.models.NullableCharField(blank=True, max_length=100, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('org_insta', events.models.NullableCharField(blank=True, max_length=500, null=True)),
                ('org_linkedin', events.models.NullableCharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', events.models.NullableCharField(blank=True, max_length=500, null=True)),
                ('event_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('coordinator_name', events.models.NullableCharField(blank=True, max_length=500, null=True)),
                ('coordinator_contact', events.models.NullableCharField(blank=True, max_length=10, null=True)),
                ('address_url', models.URLField(blank=True, null=True)),
                ('entry_fees', events.models.NullableCharField(blank=True, max_length=500, null=True)),
                ('last_date_register', models.DateTimeField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_image', models.ImageField(default='images/default.png', upload_to='events/')),
                ('no_of_applicants', models.IntegerField(blank=True, null=True)),
                ('sport_type', models.CharField(choices=[('individual', 'INDIVIDUAL'), ('team', 'TEAM')], default='individual', max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('price', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.interestmodel')),
                ('event_organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.organizers')),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_dates', to='events.eventmodel')),
            ],
        ),
    ]
